project/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'restaurants#index', as: 'restaurant_index'
  resources :restaurants, except: [:edit, :destroy]
  resources :votes, except: [:edit, :destroy]
  resources :comments
  patch '/restaurants/:id/upvote' => 'restaurants#upvote', as: :upvote
  patch '/restaurants/:id/downvote' => 'restaurants#downvote', as: :downvote
  get '/users/sign_in' => 'devise/sessions#new', as: :login
  get '/users/sign_out' => 'devise/sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

project/app/models/restaurant.rb
class Restaurant < ApplicationRecord
 validates :name, :location, presence: true
 validates :name, uniqueness: true
 has_many :votes
 has_many :comments

 def self.upvotes(id)
   votes = Vote.all
   sum = 0
   votes.each do |vote|
     if id == vote.restaurant_id and vote.voted == true
       sum += 1
     end
   end
  return sum
 end

 def self.downvotes(id)
   votes = Vote.all
   sum = 0
   votes.each do |vote|
     if id == vote.restaurant_id and vote.voted == false
       sum += 1
     end
   end
  return sum
 end

  def self.search(search)
  where("name LIKE ? OR location LIKE ?", "%#{search}%", "%#{search}%") 
  end

end

project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :vote
  has_many :comments
end

project/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :update]

  # GET /comments
  # GET /comments.json
  def index
    redirect_comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  redirect_to :back
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :restaurant_id, :message)
    end
	
	private
	def redirect_comments
		redirect_to restaurants_path
	end

end

project/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, :except => [:index, :show]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
    if params[:search]
      @restaurants = Restaurant.search(params[:search])
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @userStr = "<b>User: </b>".html_safe
    @restaurantName = "&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp<b>Restaurant: </b>".html_safe
    @commentStr = "&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp<b>Comment: </b>".html_safe
    @timeStr = "&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp<b>Created at: </b>".html_safe
    @comments = @restaurant.comments.all
    @comment = @restaurant.comments.build
    if current_user
      @sheets = current_user.id
    else
      redirect_to new_user_session_path, notice: 'You are not logged in.'
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def upvote
    @vote = Vote.new(user_id: current_user.id, restaurant_id: @restaurant.id, voted: true)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @restaurant, notice: 'Your vote was added' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def downvote
    @vote = Vote.new(user_id: current_user.id, restaurant_id: @restaurant.id, voted: false)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @restaurant, notice: 'Your vote was added' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location)
    end
    
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/comments_helper.rb
module CommentsHelper
end

project/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

project/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<% if current_user != nil && @restaurant != nil %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
<% end %>
<div class="field">
<%= f.label "Enter a message:" %><br>
<%= f.text_area :message %><br>
</div>
<div class="actions">
<%= button_to 'Add comment' %>
</div>

<% end %>

project/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

project/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.email %></td>
        <td><%= comment.restaurant.name %></td>
        <td><%= comment.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

project/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

project/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user.email %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @comment.restaurant.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @comment.message %>
</p>

<%= link_to 'Back', comments_path %>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <%= yield %>
  </body>
</html>

project/app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

project/app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Restaurants" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Up votes</th>
      <th>Down votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td><%= Restaurant.upvotes(restaurant.id) %></td>
        <td><%= Restaurant.downvotes(restaurant.id) %></td>
        <td><%= link_to 'Show', restaurant %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %><br>
<% if user_signed_in? %>
<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
<% else %>
<%= link_to 'Login', new_user_session_path %>
<% end %>

project/app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

project/app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @restaurant.location %>
</p>

<p>
  <strong>Up votes:</strong>
  <%= Restaurant.upvotes(@restaurant.id) %>
</p>

<p>
  <strong>Down votes:</strong>
  <%= Restaurant.downvotes(@restaurant.id) %>
</p>

<%= button_to "Upvote", upvote_path, method: 'patch' , params: {id: @restaurant.id} %><br>
<%= button_to "Downvote", downvote_path, method: 'patch', params: {id: @restaurant.id} %><br>

<%= render 'comments/form' %>

<h3>Comments:</h3>
<% @comments.reverse.each do |comment| %>
	<% if comment.restaurant.name == @restaurant.name %>
		<div>
		<%= @userStr %>
		<%= comment.user.email %><br>
		<%= @restaurantName %>
		<%= comment.restaurant.name %><br>
		<%= @commentStr %>
		<%= comment.message %><br>
		<%= @timeStr %>
		<%= comment.created_at %>
		<br><br>
		</div>
	<% end %>
<% end %>

<%= link_to 'Back', restaurants_path %>